---
- name: Basic Linux Setup
  hosts: localhost
  become: yes
  tasks:

    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install essential packages
      apt:
        name:
          - curl
          - git
          - vim
        state: present

    - name: Install and configure UFW
      apt:
        name: ufw
        state: present

    - name: Allow OpenSSH through firewall
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable the firewall
      command: ufw --force enable

    - name: Create a new user and add to sudo group
      user:
        name: "{{ new_user }}"
        password: "{{ new_password | password_hash('sha512') }}"
        groups: sudo
        state: present

    - name: Check disk usage
      command: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"

    - name: Check memory usage
      command: free -h
      register: memory_usage

    - name: Display memory usage
      debug:
        msg: "{{ memory_usage.stdout_lines }}"

    - name: Check system uptime
      command: uptime
      register: system_uptime

    - name: Display system uptime
      debug:
        msg: "{{ system_uptime.stdout_lines }}"

